#include<bits/stdc++.h>
#define fi(x) for(int i=0; i<x; ++i)
using namespace std;

int main(){
    int n,x,s;
    char c;
    cin>>n;
    while (n--)
    {
        cin>>x;
        s=0;
        fi(x){
            cin>>c;
            if(c=='a'){
                if(1>s){
                    s=1;
                }
            }
            if(c=='b'){
                if(2>s){
                    s=2;
                }
            }
            if(c=='c'){
                if(3>s){
                    s=3;
                }
            }
            if(c=='d'){
                if(4>s){
                    s=4;
                }
            }
            if(c=='e'){
                if(5>s){
                    s=5;
                }
            }
            if(c=='f'){
                if(6>s){
                    s=6;
                }
            }
            if(c=='g'){
                if(7>s){
                    s=7;
                }
            }
            if(c=='h'){
                if(8>s){
                    s=8;
                }
            }
            if(c=='i'){
                if(9>s){
                    s=9;
                }
            }
            if(c=='j'){
                if(10>s){
                    s=10;
                }
            }
            if(c=='k'){
                if(11>s){
                    s=11;
                }
            }
            if(c=='l'){
                if(12>s){
                    s=12;
                }
            }
            if(c=='m'){
                if(13>s){
                    s=13;
                }
            }
            if(c=='n'){
                if(14>s){
                    s=14;
                }
            }
            if(c=='o'){
                if(15>s){
                    s=15;
                }
            }
            if(c=='p'){
                if(16>s){
                    s=16;
                }
            }
            if(c=='q'){
                if(17>s){
                    s=17;
                }
            }
            if(c=='r'){
                if(18>s){
                    s=18;
                }
            }
            if(c=='s'){
                if(19>s){
                    s=19;
                }
            }
            if(c=='t'){
                if(20>s){
                    s=20;
                }
            }
            if(c=='u'){
                if(21>s){
                    s=21;
                }
            }
            if(c=='v'){
                if(22>s){
                    s=22;
                }
            }
            if(c=='w'){
                if(23>s){
                    s=23;
                }
            }
            if(c=='x'){
                if(24>s){
                    s=24;
                }
            }
            if(c=='y'){
                if(25>s){
                    s=25;
                }
            }
            if(c=='z'){
                if(26>s){
                    s=26;
                }
            }
        }
        cout<<s<<"\n";
    }
    return 0;
}